### ISSUE TITLE
step-by-step HOL instructs to deploy app service instead of ASE

### ISSUE THREAD

**Issue by SedatYogurtcuoglu** [Microsoft/MCW-Modern-cloud-apps#1]
Although the HOL states that the solution has to be PCI compliant, the apps are asked to be deployed to App service, but not ASE. Either the deployment environment needs to be changed to ASE, or the reason for not using ASE in HOL, needs to be explained.

**Comment by DawnmarieDesJardins** [comment]
Hi Michael,
Your email said this test/fix was complete, but there's an open issue.  Do the documents need to be updated?

**Comment by mwasham** [comment]
When the abstract for the lab is written by Joel I would suggest removing the PCI compliance aspect since that is specific to the WDS and not the lab.

**Comment by DawnmarieDesJardins** [comment]
Hey Joel,  
Can you please double check the workshop abstracts per Sedat & Michael's notes above?
Appreciate it!  
Dawnmarie

**Comment by joelhulen** [comment]
I made this clear under the HOL section of the main readme file.
