### ISSUE TITLE
Sept-2018-Test-Fix Ready for QA

### ISSUE THREAD

**Issue by deltadan** [Microsoft/MCW-Modern-cloud-apps#18]
The Sept-2018-Test-Fix is ready for QA.  The compliance checks have run and they are passing.  Please let me know if you need anything.

Dan.

**Comment by DawnmarieDesJardins** [comment]
Thanks Dan.  I opened two issues for you on this one.  There's some alt-text corrections that need to be sorted on the PPTs and two lines in the HOL if you could take a peek please.  (They might be fine, the formatting looks a little off to me so I'd like you to verify please.)  Once those two issues are closed, I'll merge and update HTML files.  Please email me the compliance check .xlsx and the compliance checklist so I can file it on my end.  This is a Boot Camp workshop so I need to complete it by EOD tomorrow please.

**Comment by DawnmarieDesJardins** [comment]
Completed, closing issue.
