### ISSUE TITLE
WDS trainer presentation (PPT) & Preferred Solution (PPT)

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Modern-cloud-apps#19]
Slide 15 - missing alt-text
Slide 16 - alt-text is on each individual image but reader doesn't know how to read.  Image needs to be flat and alt-text updated
Slide 19 - same as above

All slides - please check all slides to make sure images are flat with alt-text.  Example, slide 4 has one box for the full image with correct alt-text, but there is also a box for the Contoso logo and a box for the Azure web app icon that does not have alt-text.  The accessibility checker is seeing all of those as missing alt-text.  Screen shots need to be taken of the final image and the remaining boxes need to be removed.

**Comment by deltadan** [comment]
Updates completed fixing the Alt Text and to flatten images.

**Comment by DawnmarieDesJardins** [comment]
Completed, closing.
