### ISSUE TITLE
Lab guide need to be updated.( Steps related to : Azure Functions and Application insight)

### ISSUE THREAD

**Issue by fasalzaman** [Microsoft/MCW-Modern-cloud-apps#21]
In Exercise 4 > Task 1 > Subtask 2 > Step 3

In the Azure portal, under the 'configure' menu, 'Getting started' option is not available

In Exercise 5 > Task 1 > Step 4

According to the lab guide, we should select 'Generic WebHook' option, which is not available in the Azure portal. The lab guide should get updated according to the latest Azure Portal updates.

**Comment by DawnmarieDesJardins** [comment]
Thanks fasalzaman.  This workshop will be going through a test/fix in November.  I've added the author for awareness.

**Comment by DawnmarieDesJardins** [comment]
@soupman98 
Hi Steve,
Please verify this was addressed in the November test/fix and comment/close as necessary.

**Comment by soupman98** [comment]
I’ll jump on this tomorrow. I can’t recall specifically off hand if it was or not.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by soupman98** [comment]
Thanks for you feedback and contribution @fasalzaman.
These have been addressed in the Nov 2018 updates for the MCW Cloud App materials

**Comment by soupman98** [comment]
Hello and Happy New Year Dawnmarie,

This has been addressed in the November 2018 update.
I’ll look to close it as well in GH

Thanks
Steve Campbell
