### ISSUE TITLE
Subtask 2: Configure cross-origin resource sharing (CORS) - Step 2

### ISSUE THREAD

**Issue by andresravinet** [Microsoft/MCW-Modern-cloud-apps#22]
Hi.

Shouldn't Step 2 be the URL of the ContosoSports Web App URL, instead of the Offer API URL?

"In the ALLOWED ORIGINS text box, specify the URL of the Offers Web API App (can be found in the Overview link), and click Save."

**Comment by deltadan** [comment]
The instructions for this have been updated to say * instead of the URL mentioned in previous versions.

**Comment by DawnmarieDesJardins** [comment]
Issue addressed, closing.
