### ISSUE TITLE
March 2019 - Scheduled content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Modern-cloud-apps#28]
@ZoinerTejada @joelhulen @kylebunting
Solliance team -
This workshop is scheduled for an update in March. Please update this issue with suggested content changes. Once done, we'll assign to our SME team for review and additional feedback.

**Comment by ZoinerTejada** [comment]
The primary update suggested by the team is to upgrade to v2 of Azure Functions. It's a minor update, but we feel this one is pretty comprehensive. As always we are open to further input.

**Comment by DawnmarieDesJardins** [comment]
@ZoinerTejada 
Received lead sign off to move forward with this update with suggestions given.  Please see open issue #29 while updating.

**Comment by DawnmarieDesJardins** [comment]
Closing as complete with March update
