### ISSUE TITLE
Starter Solution is the finished solution

### ISSUE THREAD

**Issue by mwasham** [microsoft/MCW-Modern-cloud-apps#29]
Starter project is incorrect. It is actually not the starter project but the finished project.  It has code added in the exercises for Identity, existing publish profiles etc...

**Comment by DawnmarieDesJardins** [comment]
@ZoinerTejada 
Hi Zoiner, you're scheduled to do a March update on this one.  Please review Michael's comment.

**Comment by timahenning** [comment]
I have fixed this in my upcoming update.

**Comment by DawnmarieDesJardins** [comment]
Closing as addressed in March update
