### ISSUE TITLE
November 2019 - Content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Modern-cloud-apps#39]
This workshop is scheduled for a content update. Solliance, please review the workshop and provide your update suggestions for SME review here.

**Comment by crpietschmann** [comment]
Here are some suggested updates to make to the MCW:

1. In the "Before HOL" guide change the ARM Template deployment to use a "Deploy to Azure" link button that deep links into the Azure Portal automatically pulling in the ARM Template; just like the Azure Quickstart Templates does (https://azure.microsoft.com/en-us/resources/templates/ubuntu-desktop-gnome-rdp/). This will streamline the initial "Before HOL" deployment further.

2. Change from using Storage Queues to using Event Grid for the messaging that kicks off the Logic App and Azure Function for a more modern Event Driven Serverless architecture.

3. Upgrade Web and API apps to .NET Core and ASP.NET Core so they are up-to-date with the current state of the .NET ecosystem. This is more than just updating the version number, it will require making code changes to do.

These are a few initial suggestions. Let me know what you think.

**Comment by kylebunting** [comment]
@crpietschmann I would suggest we also include the following in the update:

1. For both the WDS and HOL documents, you should include a statement in the `Requirements` section that they need to have sufficient permissions in their Azure Subscription Azure AD tenant to create users and set up Azure AD B2C.

2. Move all resource provisioning into the before the hands-on lab document. Preferably, it could all be done with an ARM template, but at a minimum handle creating all resources in the before the HOL document.

3. Add the use of Key Vault for securing application secrets.

    - For all steps that require adding connection strings into App Service configuration settings, use [Key Vault references](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references). This should also be mentioned in the whiteboard design documents, as it allows secrets to be managed and provided to applications without developers ever needing to see or know the secrets.
    - Set up managed identities for each of the App Services and assign an access policy for each that allows `Get` on secrets.
    - Add the database connection string as a secret in Key Vault.
    - Add the queue connection string as a secret in Key Vault.

4. For Exercise 1, Task 2: 

    - Change this to use auto-failover groups. Failover using this is fast, so it can be tested within the time constraints of the lab.
    - Have users update the connection string of the e-commerce website to use the read-write listener endpoint of the failover group. (This would happen in Key Vault and provide a new version of the secret.)
       - Include `ApplicationIntent=ReadOnly;` at the end of the connection string, and point out the significance of this to users.
    - Failover the database and show that no app changes were required. This will allow the failover to happen without the need to update the connection string in the application.

5. For Exercise 1, Task 5 (Offers API):

    - Add a new read-only database connection string into Key Vault (`ContosoSportsLeagueReadOnly`) that references the read-only listener endpoint of the failover group.
    - Configure the Offers API to use the read-only listener endpoint of the failover group. This will demonstrate how read-only workloads can be pointed to a read-only secondary to lessen the impact of reading from the primary database.
    - Since the Offers API is using Swagger, perhaps add a few steps to have the users navigate to the Swagger UI, select the Offers endpoint and "Try it out."

**Comment by DawnmarieDesJardins** [comment]
Hello, We have lead approval to move forward with an update draft.  Thank you!

**Comment by crpietschmann** [comment]
@kylebunting Thanks for the input on updates to make. I'll look at incorporating these, as they are good ideas for a  "modern cloud app". I'll just need to make sure everything will fit into the lab time, and it doesn't make the lab too long. I don't think it'll be an issue, but I'll assess appropriately before incorporating changes.

**Comment by crpietschmann** [comment]
The items that were suggested here that were not able to be added / modified with the November 2019 (via PR #40 ) update have been added as Issues to this repo. This will ensure they aren't forgotten and we can track them for a future round of updates / changes to the MCW.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with PR #40 merge
