### ISSUE TITLE
Exercise 1 - task 6 - subtask 2

### ISSUE THREAD

**Issue by jamespearse80** [microsoft/MCW-Modern-cloud-apps#41]
I have run through all the content and deployed the applicable services. When I go to checkout (with default values) I get an checkout error "no valid combination of account information found"

**Comment by jamespearse80** [comment]
As an FYI I am carrying out a cut down version of this workshop next week for the International Red Cross (just doing Exercise 1) - I have built my own lab out to try everything out, all goes well until the last task (as mentioned above)

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  

Having specific lab section references and screenshots will help expedite support. We will review your issue soon.

Tim

**Comment by crpietschmann** [comment]
@jamespearse80 I am unable to duplicate this error. Could you post a screenshot of the error message? Also, have you verified all the configuration settings are set correctly on the web apps?

**Comment by jamespearse80** [comment]
@crpietschmann Thanks for looking!! you are correct, I went back through the lab step by step and discovered that I had inadvertently copied the storage key and not the connection string (Task 1 - subtask 2) after changing this it worked as expected :)

Many thanks
