### ISSUE TITLE
Add use of Key Vault for securing application secrets

### ISSUE THREAD

**Issue by crpietschmann** [microsoft/MCW-Modern-cloud-apps#43]
Add the use of Key Vault for securing application secrets.

- For all steps that require adding connection strings into App Service configuration settings, use Key Vault references. This should also be mentioned in the whiteboard design documents, as it allows secrets to be managed and provided to applications without developers ever needing to see or know the secrets.
- Set up managed identities for each of the App Services and assign an access policy for each that allows Get on secrets.
- Add the database connection string as a secret in Key Vault.
- Add the queue connection string as a secret in Key Vault.

**Comment by estensen** [comment]
Wouldn't it be better to use Managed Identity instead of storing the database connection in Key Vault? To get automatically key rotation and not having to expose it to put it in Key Vault.

**Comment by crpietschmann** [comment]
@estensen Using Managed Identity is a nice idea to add. However, with the current length of the lab, I believe adding the steps in for this in addition to everything else will make the lab too long in duration. Also, with the app using .NET Core 3 and the documentation listed .NET Core 2.2; we'd also have to make sure this will work with .NET Core 3.

For reference, here's a docs article on setting up App Service with Managed Identity for a Azure SQL Database: <https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi>

Overall, I'll suggest for the next update, we add the Key Vault integration

**Comment by crpietschmann** [comment]
Also, mostly due to troubleshooting the Auth issues, I wasn't able to get to the KeyVault (#43) and EF Core Seeding (#52) changes in the March 2020 Update, so those will need to be left for a future update/fix cycle.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #71
