### ISSUE TITLE
Web App not opening after publishing it with the correct connection strings

### ISSUE THREAD

**Issue by Suraj2093** [microsoft/MCW-Modern-cloud-apps#46]
In Exercise 1 subtask 4, the Web App not opening after publishing it with the correct connection strings. When we try to open the web app in a browser, it displays as follows

![image](https://user-images.githubusercontent.com/30050847/72731183-30af3a00-3bb9-11ea-8330-677014b99564.png)

**Comment by crpietschmann** [comment]
Makes sure there aren't any errors in the config file and the connection strings are set correctly.

I have seen this error come up some times, and to fix it I needed to Restart the App Service for the app and redeploy the code. There have been times where I had to delete the App Service Web App resource in Azure, and create a new one, deploy, and then it worked.

Here's the troubleshoot description Microsoft has in the docs for this error message:

```
The worker process fails. The app doesn't start.

The ASP.NET Core Module attempts to start the .NET Core CLR in-process, but it fails to start. The cause of a process startup failure can usually be determined from entries in the Application Event Log and the ASP.NET Core Module stdout log.

A common failure condition is the app is misconfigured due to targeting a version of the ASP.NET Core shared framework that isn't present. Check which versions of the ASP.NET Core shared framework are installed on the target machine.
```
https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1

**Comment by timahenning** [comment]
Closing issue as no further response from the field.  I will reopen if needed.
