### ISSUE TITLE
Database initialization in Contoso.Apps.SportsLeague.Admin

### ISSUE THREAD

**Issue by christiannagel** [microsoft/MCW-Modern-cloud-apps#47]
In the Startup class of the project Contoso.Apps.SportsLeague.Admin, the ProductContext can be disposed before the Configure method is completed.
The Configure method is not awaited.

Options for a fix:

-  using Wait() like in the project Contoso.Apps.SportsLeague.Web
- using await
- injecting the ProductContext with the Configure method of the Startup class

**Comment by christiannagel** [comment]
There's the same issue with the Contoso.Apps.SportsLeague.Offers API project in the Configure method of the Startup class.

**Comment by crpietschmann** [comment]
Thanks for brining this up. We'll look at this update when we assess the next update to this MCW.

**Comment by christiannagel** [comment]
With the next update it's probably a good idea to change the initialization of the database to use the EF Core seeding feature (HasData on configuring of the model in the context-class) instead of the current implementation.

**Comment by thiagofborn** [comment]
Is there any chance of this issue be fixed before February 7? 

Or if you guys don't mind, would it be possible to have the Startup class source changes shared with me?

**Comment by crpietschmann** [comment]
I added the `.Wait()` call to the Admin Startup.cs and committed this change to the repo. This is the simplest solution to the issue brought up.

I'm not sure exactly how much work to move to EF Core seeding will be involved at this time; without further evaluation. I think we'll need to assess this when we go to do the next update of the MCW, and see if it fits within the time/budget allocated along with all the other required changes/updates.

Thanks for bringing this up!

**Comment by timahenning** [comment]
> With the next update it's probably a good idea to change the initialization of the database to use the EF Core seeding feature (HasData on configuring of the model in the context-class) instead of the current implementation.

I have created a new issue with this request.

**Comment by timahenning** [comment]
Chris updated Startup.cs as requested.  I created a new issue enhancement for EF Core seeding.
