### ISSUE TITLE
Exercise 4: Task 2: VSTS Account creation failed

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Modern-cloud-apps#48]
[Exercise 4: Task 2:](https://github.com/microsoft/MCW-Modern-cloud-apps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Modern%20cloud%20apps.md#subtask-1-create-the-load-test) The account creation is failing and giving error message: **VSTS Account creation failed**

![image](https://user-images.githubusercontent.com/50323628/72988824-0a84d680-3e13-11ea-9119-460a5a29bdf5.png)

Can you please check and let me know the reason this is failing?

**Comment by SeeratArora** [comment]
Do we have any updates on this?

**Comment by timahenning** [comment]
We have submitted a PR today. It should be published today or tomorrow.

**Comment by akn9050** [comment]
hi @timahenning any update on this

**Comment by crpietschmann** [comment]
Hi @akn9050, I have tested this myself and everything seems to be working as expected. I'm suspecting this might be some kind of transient error within the Azure Portal. Have you tried creating the DevOps Organization again?

If it keeps failing for you, you may want to file a support ticket with Azure Support to so they can look at it. Thanks!

**Comment by crpietschmann** [comment]
Hi @akn9050 and @SeeratArora, I have tested this myself and everything seems to be working as expected. I'm suspecting this might be some kind of transient error within the Azure Portal. Have you tried creating the DevOps Organization again?

If it keeps failing for you, you may want to file a support ticket with Azure Support to so they can look at it. Thanks!
