### ISSUE TITLE
Change Azure Data Warehouse to Azure Synapse Analytics

### ISSUE THREAD

**Issue by christiannagel** [microsoft/MCW-Modern-cloud-apps#49]
With the whiteboard design session, in the slides and in [WDS student guide](https://github.com/microsoft/MCW-Modern-cloud-apps/blob/master/Whiteboard%20design%20session/WDS%20student%20guide%20-%20Modern%20cloud%20apps.md) the term **Azure Data Warehouse** is used. This has been renamed to **Azure Synapse Analytics**.

See: https://azure.microsoft.com/en-us/blog/azure-sql-data-warehouse-is-now-azure-synapse-analytics/

**Comment by crpietschmann** [comment]
I just submitted a commit that includes this rebranding change to the WDS guides and slides to change the product name from "Azure SQL Data Warehouse" to "Azure Synapse Analytics".
Thanks for pointing this one out!
