### ISSUE TITLE
.NET Core 3.0 End of Support March 3, 2020

### ISSUE THREAD

**Issue by christiannagel** [microsoft/MCW-Modern-cloud-apps#50]
With .NET Core 3.0 end of support on March 3, 2020 it would be a good idea to update the sample app to .NET Core 3.1.

[.NET Core Support Policy](https://dotnet.microsoft.com/platform/support/policy/dotnet-core)

I can create a pull request.

**Comment by crpietschmann** [comment]
The next update for this one should include this change to update the app to .NET Core 3.1; which is an LTS release. We'll have to consider this for the next update to the MCW. Thanks for bringing this up!

Also, for reference, here's a page that as a list of the LTS released and support dates of .NET Core: <https://dotnet.microsoft.com/platform/support/policy/dotnet-core>

**Comment by crpietschmann** [comment]
This is being incorporated in the update, as listed in Issue #58

**Comment by crpietschmann** [comment]
This has been incorporated as part of the March 2020 update (#58), so I'm closing this Issue out.
