### ISSUE TITLE
With the next update it's probably a good idea to change the initialization of the database to use the EF Core seeding feature (HasData on configuring of the model in the context-class) instead of the current implementation.

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Modern-cloud-apps#52]
With the next update it's probably a good idea to change the initialization of the database to use the EF Core seeding feature (HasData on configuring of the model in the context-class) instead of the current implementation.

_Originally posted by @christiannagel in https://github.com/microsoft/MCW-Modern-cloud-apps/issues/47#issuecomment-579728704_

**Comment by crpietschmann** [comment]
This change makes sense being the app is now .NET Core. Thanks @christiannagel

Here's a documentation link: <https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding>

**Comment by crpietschmann** [comment]
Also, mostly due to troubleshooting the Auth issues, I wasn't able to get to the KeyVault (#43) and EF Core Seeding (#52) changes in the March 2020 Update, so those will need to be left for a future update/fix cycle.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #71
