### ISSUE TITLE
Azure AD B2C Exercise 3

### ISSUE THREAD

**Issue by christiannagel** [microsoft/MCW-Modern-cloud-apps#54]
Exercise 3 has some issues. 

## Task 5
Task 5 mentions to add `UseAuthorization`. However, this API call is already in the source code. Instead, `UseAuthentication` needs to be added.

In the `ConfigureServices` method, the information to add `AddAuthentication` is missing. I was successful in adding this (this is the same code as generated from the default template when selecting Azure AD B2C for identity).

```csharp
            services.AddAuthentication(AzureADB2CDefaults.AuthenticationScheme)
                .AddAzureADB2C(options => Configuration.Bind("AzureAdB2C", options));
```

## Task 6

The image to add a controller is from the .NET Framework version. This should be changed to the ASP.NET Core version.

In the AccountController, instead of using `HttpContext.Challenge`, the `Challenge` method of the base class can be used.

## Task 7

With ASP.NET Core, `ClaimsPrincipal.Current` returns null, as documented here:

https://docs.microsoft.com/en-us/aspnet/core/migration/claimsprincipal-current?view=aspnetcore-3.1

I've changed the Claims method in the HomeController:

```csharp
        [Authorize]
        public ActionResult Claims()
        {
            var displayName = User.Identity.Name;
            ViewBag.DisplayName = displayName;
            ViewBag.Claims = User.Claims;
            return View();
        }
```

The code for the view also needs to be changed:

```razor
    @foreach (Claim claim in ViewBag.Claims)
    {
        <tr>
            <td class="claim-type claim-data">@claim.Type</td>
            <td class="claim-data">@claim.Value</td>
        </tr>
    }
```

**Comment by christiannagel** [comment]
To reduce the amount of time needed to implement B2C, with ASP.NET Core it is not necessary to create an Account controller. Instead the pre-built library implementation can be used. 
To see this, with the ASP.NET Core MVC project template, selecting authentication with Azure B2C defines the code needed.

All what needs to be done with the implementation (other than the configuration) is to change the links in *_LoginPartial.cshtml*, and the Account controller can be removed.

**Comment by DawnmarieDesJardins** [comment]
@timahenning @crpietschmann 
Please review & advise

**Comment by crpietschmann** [comment]
Thanks @christiannagel for the suggestions. We'll incorporate these changes into the next update.

**Comment by aautere** [comment]
I had some hard time with the Exercise 3 so we made some improvements with [juunas1](https://github.com/juunas11) (or it was mainly juunas11 who did these 😄). Feel free to [use them](https://github.com/aautere/MCW-Modern-cloud-apps/commits/master/Hands-on%20lab/HOL%20step-by-step%20-%20Modern%20cloud%20apps.md) if you like :)

**Comment by crpietschmann** [comment]
@christiannagel  Do you have a full example app for using Azure AD B2C with ASP.NET Core 3.1? No matter what I do, the Signin/Signup pages in the site always give a 404 response. When using the `Challenge` methods (as I modified the lab) the ChallengeResult returns a 404 to the browser. I also created a brand new project using Visual Studio and it even returns 404 responses for the `/AzureADB2B/Account/SignIn` URL as well... It really seems like this functionality is just plain broken with ASP.NET Core 3.1. Do you have any insights you can offer for getting this piece working? I appreciate any input you can give. Thanks!

**Comment by andresmmujica** [comment]
@crpietschmann take a look at @aautere commits in his fork, you'll be able to resolve those 404 errors.

**Comment by christiannagel** [comment]
@crpietschmann I had it running in a branch in my fork as well:  https://github.com/christiannagel/MCW-Modern-cloud-apps.

Did you get the 404 errors when running the application on the local system? Then the URL needs to be modified in the app registration.

The lab now includes signup/sign-in and edit user flows. but not a reset password user flow. Signup/sign-in and reset password are mandatory user flows. This could be a reason for 404 as well. 

A minor note: just recently they changed **User Flows (Policies)** to just **User Flows** in the portal.

I'll test it now and will give you more information in a few hours.

**Comment by christiannagel** [comment]
@crpietschmann, I've created a pull request to your branch with changes on the Lab.

I had one other sample where I didn't use the custom Account controller but the built-in user interfaces. This requires the reset password user flow. With the custom Account controller this flow is not needed.

With the pull request I've changed the labs for the Account controller with changes to invoke the Challenge API, and a fix in the link to the configuration of the Instance key for the AzureADB2C configuration.

**Comment by crpietschmann** [comment]
@christiannagel I added steps to create the Password reset policy, as that really should be there anyway. Although that didn't fix things for me. And, I'm running it in the App Service when I get 404's, just to clarify. I'm going to keep troubleshooting this for now, please update me with any insights you find. Thanks!

**Comment by crpietschmann** [comment]
@christiannagel Thanks! I went through your changes, fixed my branch, and got it working! :) One thing was the `AzureADB2C:Instance` was pointing to the wrong URI. Thank you very much for the help!

I'm closing this issue now that the changes have been incorporated into the `Update-March-2020` (#58) branch, and this has been fixed.
