### ISSUE TITLE
Exercise 1, Task 5: Offers Web API UseCors

### ISSUE THREAD

**Issue by christiannagel** [microsoft/MCW-Modern-cloud-apps#55]
With ASP.NET Core 3.x, the `UseCors` API Contoso.Apps.SportsLeague.Offers, Startup.cs needs to be positioned after UseRouting and before UseEndpoints. Cors errors are returned otherwise.

See this documentation:
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#migrate-startupconfigure

**Comment by DawnmarieDesJardins** [comment]
@timahenning @crpietschmann 
Please review & advise

**Comment by crpietschmann** [comment]
I made this change. Thanks!
