### ISSUE TITLE
async issue with Edit in CartController

### ISSUE THREAD

**Issue by christiannagel** [microsoft/MCW-Modern-cloud-apps#56]
The `Edit` method (HttpPost version) in the CartController (project Contoso.Apps.SportsLeague misses an **await** on _db.SaveChangesAsync. This leads to rollbacks because the context is disposed before the method is completed.

The await keyword should be added (the method is already in async scope).

CartController.cs:
await _db.SaveChangesAsync();

**Comment by DawnmarieDesJardins** [comment]
@timahenning @crpietschmann 
Please review & advise

**Comment by timahenning** [comment]
We need to test the fixes and run the entire lab.  We should have an update by this weekend.

**Comment by crpietschmann** [comment]
I have made this change. Thanks!
