### ISSUE TITLE
Add Azure App Configuration

### ISSUE THREAD

**Issue by christiannagel** [microsoft/MCW-Modern-cloud-apps#61]
With the next round of updates I think it would be a good idea to add **Azure App Configuration**. With this service all configurations for the solution can be retrieved. With secrets, *Azure App Configuration* can be configured to access the *Azure Key Vault*. 

See: https://docs.microsoft.com/en-us/azure/azure-app-configuration/overview

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #71
