### ISSUE TITLE
Exercise 5 - Task2 - SQL UPDATE not available.  Only v2 is available

### ISSUE THREAD

**Issue by andresmmujica** [microsoft/MCW-Modern-cloud-apps#62]
Hi guys, we're having an issue with the Exercise 5   Task  2, the widget requested seems to be not longer available, and it's not clear how to configure it.  Please advice.

**Comment by crpietschmann** [comment]
@andresmmujica Yes, the SQL Update action within Logic Apps has been removed for new Logic Apps, and only the V2 action is currently available. It works the same, but the JSON definition is slightly different. Feel free to reference the [Update-March-2020 branch](https://github.com/microsoft/MCW-Modern-cloud-apps/tree/Update-March-2020) as that has been recently updated with the current state as part of the update we are working on for the MCW.

**Comment by andresmmujica** [comment]
awesome ! thanks :)
