### ISSUE TITLE
Exercise 5 Task 2 - QUEUES not working 

### ISSUE THREAD

**Issue by andresmmujica** [microsoft/MCW-Modern-cloud-apps#64]
We're not able to see the messages in the blob neither the PDF files, it works for the manual test of the PDF Function, it leaves the PDF file in the Message queue inside the blob.  However, when we click play on the Logic App it shows a success message but it doesn't generate any message in the queue neither a PDF file in the blob.

**Comment by crpietschmann** [comment]
When submitting the order the Phone number field isn't populated, but is required for the submission to go through correctly. Be sure to enter that field, and it should work.

**Comment by crpietschmann** [comment]
I updated the student files to include this fix, so the field will default to have a value.
