### ISSUE TITLE
Missing Service Bus Queue in Resources deployed during the lab - queue issues

### ISSUE THREAD

**Issue by andresmmujica** [microsoft/MCW-Modern-cloud-apps#65]
Hey guys, we still have queue issues and following the update, we identified that this is not created:

Task 1: Deploy the e-commerce website, SQL Database, and storage
Subtask 3: Retrieve Service Bus Queue Connection String

this is the object we cannot find and we're not sure how to create it from scratch.

https://raw.githubusercontent.com/microsoft/MCW-Modern-cloud-apps/Update-March-2020/Hands-on%20lab/media/2020-03-18-10-38-09.png

**Comment by crpietschmann** [comment]
The ARM Template located within the "Update-March-2020" branch to setup the environment includes creating the Service Bus Namespace and Queue resources. Make sure you copy the files from there, as the LabVM ARM Template is pointed to pull .zip files from 'master' branch so there's no conflict when these changes are merged later.
