### ISSUE TITLE
Exercise 3: Task 9: The Sign Up, Sign In and Claims page is not loading as required.

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Modern-cloud-apps#66]
[Exercise 3 :Task 9:](https://github.com/microsoft/MCW-Modern-cloud-apps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Modern%20cloud%20apps.md#task-9-run-the-sample-app) The Sign Up, Sign In and Claims page is not working properly as mentioned in the lab guide. It gets directed to the page showing 'Today's offers'(as shown below):

![image](https://user-images.githubusercontent.com/50323628/80341569-4ef39880-8880-11ea-9726-77008d8f7864.png)

As a workaround we figured out that:

If we add the **AzureADB2C:CallbackPath** from [Exercise 3 :Task 6:](https://github.com/microsoft/MCW-Modern-cloud-apps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Modern%20cloud%20apps.md#task-6-modify-the-contosoappsportsleagueweb)

![image](https://user-images.githubusercontent.com/50323628/80340597-8bbe9000-887e-11ea-90bd-3134de654a9a.png)

to the end of **Reply URL** in [Exercise 3 :Task 2:](https://github.com/microsoft/MCW-Modern-cloud-apps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Modern%20cloud%20apps.md#task-2-add-a-new-application) 

![image](https://user-images.githubusercontent.com/50323628/80340582-85301880-887e-11ea-9328-b856eb89851e.png)

For example: We have Reply URL - https://[your web url].azurewebsites.net so we add it in the configurations as **https://[your web url].azurewebsites.net/signin-oidc-b2c** and then save it. 

Thus, it works fine as we get desired result as mentioned in the lab guide for Sign Up, Sign In and Claims page.

Can you please have a look into this and take required actions?

Thanks,
Seerat

**Comment by christiannagel** [comment]
I agree, the text for exercise 3, task 2 should be changed to include signin-oidc-b2c with the URL.

**Comment by crpietschmann** [comment]
Thanks @christiannagel for the validation. I do remember this setting, but not sure how it slipped through without the path on the domain name. I just committed a fix to the repo, so this will be fixed now.
