### ISSUE TITLE
Exercise 4 - Telemetry with Application Insights using obsolete TelemetryClient

### ISSUE THREAD

**Issue by christiannagel** [microsoft/MCW-Modern-cloud-apps#67]
In exercise 4, task 1, the NuGet package Microsoft.ApplicationInsights.Web is used. The constructor used in subtask 1, step 7 is marked as obsolete.
Instead, the NuGet package Microsoft.ApplicationInsights.AspNetCore should be used:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core

Also, see [Deprecating TelemetryConfiguration.Active singleton](https://github.com/microsoft/ApplicationInsights-dotnet/issues/1152)

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #71
