### ISSUE TITLE
Exercise 4: Task 2: Creating the web performance test and load test

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Modern-cloud-apps#68]
[Exercise 4: Task 2:](https://github.com/microsoft/MCW-Modern-cloud-apps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Modern%20cloud%20apps.md#task-2-creating-the-web-performance-test-and-load-test) Performance Testing is not available in the portal.

![image](https://user-images.githubusercontent.com/50323628/85261240-7edaa900-b489-11ea-8eee-8fe063a10597.png)

Please review this.

Thanks,
Seerat

**Comment by crpietschmann** [comment]
The "Performance Testing" feature of Application Insights has been deprecated by Microsoft and has been recently removed. I am currently working on the latest revision to this MCW, and these steps will be removed from the next update to reflex these feature changes in the service.
