### ISSUE TITLE
Exercice 1 Task 1 Step 9 :  HTTP Error 500.30 - ANCM In-Process Start Failure

### ISSUE THREAD

**Issue by eliesadjal** [microsoft/MCW-Modern-cloud-apps#70]
Hello, 
When I Publish my app, VisualStudio2019 tells me that my app has been succesfully published and do not show me any error/warning.
The problem is, when I go to my Web Browser to see my app, I have this error (HTTP Error 500.30 - ANCM In-Process Start Failure) so I can not access to my web app. (I tried to use an other Web Browser, and to launch the app from the Azure portal, same result)
So I went to my Azure Portal to take a look at the Application's logs. It showed me this following error : 

[Application '/LM/W3SVC/1578876600/ROOT' with physical root 'D:\home\site\wwwroot\' failed to load coreclr. Exception message:
CLR worker thread exited prematurely
Process Id: 13212.
File Version: 13.1.20142.5. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: 844a82e37cae48af2ab2ee4f39b41283e6bb4f0e]

I do not really know how to solve this error and I hope that someone has a clue for me to be able to continue the tutorial..

Thank you in advance !

**Comment by codingbandit** [comment]
@eliesadjal - please ensure that you replaced the password  token in the connection string with demo@pass123

**Comment by crpietschmann** [comment]
Some times this error happens the first time you deploy your app to Azure App Service. I'm not sure what causes it, but setting the deployment to remove existing files before copying the new files will resolve it. Here's an explanation of this: <https://build5nines.com/fix-net-core-http-error-500-30-after-publish-to-app-service-from-visual-studio/>

**Comment by timahenning** [comment]
Closing this issue due to lack activity.  If this continues to be a problem, we can reopen the issue.
