### ISSUE TITLE
various issues faced

### ISSUE THREAD

**Issue by bonzz** [microsoft/MCW-Modern-cloud-apps#72]
Hi All,
1)
**[exercise1,task1,subtask1]**(https://github.com/microsoft/MCW-Modern-cloud-apps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Modern%20cloud%20apps.md#subtask-1-configure-sql-database-firewall-and-retrieve-connection-string)

here in step 8, we are asked to add the client IP address and when doing that when we try to publish the admin call center application, was not able to publish it

but when provided the IP address range from 0.0.0.0 to 255.255.255.255, was able to publish the call center application.

2)
**[exercise1,task4]**(https://github.com/microsoft/MCW-Modern-cloud-apps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Modern%20cloud%20apps.md#task-4-deploying-the-payment-gateway)

hereafter publishing the API application, the following error as shown in the image occurs

![image](https://user-images.githubusercontent.com/48308835/91822626-ad2cef80-ec55-11ea-9a3e-641ec97db0f5.png)

3)
**[exercise1,task5]**(https://github.com/microsoft/MCW-Modern-cloud-apps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Modern%20cloud%20apps.md#task-5-deploying-the-offers-web-api)

hereafter publishing the API application, the following error as shown in the image occurs

![image](https://user-images.githubusercontent.com/48308835/91822829-f2e9b800-ec55-11ea-857d-b0d06d6ac06e.png)

4)
**[exercise 3,task3,step 14]**(https://github.com/microsoft/MCW-Modern-cloud-apps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Modern%20cloud%20apps.md#task-3-create-policies-sign-up-and-sign-in)

here when we are trying to run the user flow we were not able to run it and also the user flow details were not shown as noticed in the image below even though the permissions were given .this scenario happened for all user flows

![image](https://user-images.githubusercontent.com/48308835/91823313-a488e900-ec56-11ea-8ae2-c7a22d960161.png)

Can you please check in to these issues.

Thanks & Regards

**Comment by crpietschmann** [comment]
1. In Ex 1, Task 1, Subtask 1, it is having you configure the firewall for the SQL Database. You need to add your machines IP address so that you can connect to the database. Adding just your IP address enables just your machine to connect. Adding the range of 0.0.0.0 - 255.255.255.255 will enable any IP address on the Internet to connect.

**Comment by crpietschmann** [comment]
@timahenning We will need to escalate the issue of the "Run user flow" dialog being empty. The [documentation](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows) shows this dialog should not be empty after configuring User flows, and something seems to not be working correctly.

**Comment by timahenning** [comment]
@bonzz We are reaching out to MS resources that can address Azure issue.

**Comment by akn9050** [comment]
hi, please let us know if any update on this.

Thanks,
Amit

**Comment by timahenning** [comment]
@akn9050 Hi, I am assuming you are referring to the Run user flow instruction.  This is an Azure controlled screen.  Have you tried it again?

**Comment by DawnmarieDesJardins** [comment]
@akn9050 
Hi Amit!  Have you tried running the lab again?

**Comment by DawnmarieDesJardins** [comment]
Closing issue, @akn9050 please reopen if you run the lab again and get the same response.
