### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by mreherefortea** [microsoft/MCW-Modern-cloud-apps#74]
Hello Team:

I noticed that in the requirements section of the before you begin, it calls for Windows Server 2016 as shown below:

![image](https://user-images.githubusercontent.com/41710326/103320091-bbb7c780-49f9-11eb-9b90-5debfd84f96b.png)

The ARM template deploys Server 2019, I assume that 2019 can be leveraged?  I just wanted to clarify please. Thank you for your time!

**Comment by saimachi** [comment]
Hello @mreherefortea,

Yes, Windows Server 2019 should work correctly, given that most of the work performed in the VM involves Visual Studio. I have opened a PR with this clarification.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #75 
Thank you!
