### ISSUE TITLE
Issue in exercise 3, task 3, step 7: no disable option available for MFA.

### ISSUE THREAD

**Issue by Eddevinc** [microsoft/MCW-Modern-cloud-apps#76]
in exercise 3, task 3, step 7: no disable option available for MFA.

![image](https://user-images.githubusercontent.com/32365275/106473260-98d17500-64c9-11eb-9139-951306d1c3c1.png)

**Comment by saimachi** [comment]
Hi @Eddevinc,

The lab does not ask you to select an option to disable MFA. That is already done by setting the **MFA enforcement** option to _Conditional (Recommended)_, and then deselecting the **Enforce conditional access policies** option, which is done in the next step.
