### ISSUE TITLE
Task 2: Deploy Lab VM Resources to Azure-VmExtensionProvisioningError

### ISSUE THREAD

**Issue by tcdaniela** [microsoft/MCW-Modern-cloud-apps#79]
Before initiating the hands-on lab, at Task 2, the task listed on the deployment progress screen as LabVM/CustomScriptExtension failed. 
![Capture](https://user-images.githubusercontent.com/40601522/107424858-70c3c080-6b1e-11eb-8e0d-80705222f28d.PNG)

**Comment by saimachi** [comment]
Hi @tcdaniela,

Thank you for bring this issue to our attention. We are updating the Custom Script Extension PowerShell script so it is able to install SSMS and extract the lab files without an issue.

If you would like to proceed with the lab before we deliver a fix in the next few days, run the following PowerShell script on the VM to install Chocolatey and SSMS, and then manually download and extract the [lab files.](https://github.com/microsoft/MCW-Modern-cloud-apps/blob/master/Hands-on%20lab/Lab-files/Modern%20Cloud%20Apps%20Student%20Files.zip) However, we look to deliver our solution soon.

```PowerShell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# Install SSMS
iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')) 
choco install sql-server-management-studio -y
```
