### ISSUE TITLE
Issue with Exercise 3, task 9

### ISSUE THREAD

**Issue by Dacuna16** [microsoft/MCW-Modern-cloud-apps#82]
I am stuck on Exercise 3, task 9. After following all the steps when trying to test either "sign up", "sign in" or "claims" I am getting a 404 error like this one (any browser, multiple endpoint devices)

Request URL: https://myWebApp.azurewebsites.net/AzureADB2C/Account/Error
Request Method: GET
Status Code: 404 Not Found

When clicking on **any** of the three buttons I see the browser is redirected to the following URL, and then immediately shows the 404 error:

https://myB2CTenant.b2clogin.com/myB2CTenant.onmicrosoft.com/b2c_1_signup/oauth2/v2.0/authorize?client_id=myAppClientID&redirect_uri=https%3A%2F%2Fcontosoapp67fo624vmrzsk.azurewebsites.net%2Fsignin-oidc-b2c&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=longChainOfCharacters&state=looongerChainOfCharacters&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0

I've followed the steps multiple times, and I've recreated my B2C tenant so I am not sure what might be causing the error here, thanks in advance.

**Comment by timahenning** [comment]
Hi @Dacuna16,

We will be looking into this over the next few business days.

**Comment by Dacuna16** [comment]
Thanks @timahenning  / @kylebunting , looking forward to hearing back from you!

**Comment by timahenning** [comment]
Hi @Dacuna16,

We are still trying to identify the issue.  Hopefully, we have update later today.

**Comment by kylebunting** [comment]
@Dacuna16, I'm pushing updates to the hands-on lab guide around this, but wanted to have to test out the fix directly, if you don't mind.

In the Azure portal, you will need to navigate to your Azure AD B2C tenant, which you can do from the `ContosoSports` resource group by selecting the **B2C tenant** resource. Once there, select the **Contoso B2C Application** you created during the steps leading up to this exercise.

On the **Contoso B2C Application** blade, select **Authentication** from the left-hand navigation menu.

![image](https://user-images.githubusercontent.com/5960229/115795793-98e16280-a39e-11eb-9227-31565abfe490.png)

On the **Authentication** blade, scroll down and locate the **Implicit grant and hybrid flows** section, and then check the boxes for **Access tokens** and **ID tokens**.

![image](https://user-images.githubusercontent.com/5960229/115795882-c3332000-a39e-11eb-9e42-3cd620de6672.png)

Select **Save** at the top of the page.

Once you've done that, please refresh the web application in the browser and then try to select any of the B2C pages (/claims, sign in, sign up).

If you continue to have issues, please let me know and I'll dig further into the issue.

**Comment by kylebunting** [comment]
@Dacuna16, one other thing to note, that I found confusing in the lab guide, is that the **AzureADB2C:Instance** setting added to the configuration for the web app should only contain the name of your Azure AD B2C tenant, not the full domain URL. The value should look something like the below, with your tenant name replacing `contososportsorg`:

![image](https://user-images.githubusercontent.com/5960229/115796135-494f6680-a39f-11eb-9008-2adefb9c7fb5.png)

**Comment by Dacuna16** [comment]
Thanks guys, everything is working fine now after applying the recommended changes!

**Comment by kylebunting** [comment]
@Dacuna16, excellent, and thanks for the follow-up to confirm.
