### ISSUE TITLE
Call Center app AAD authentication issue

### ISSUE THREAD

**Issue by Dacuna16** [microsoft/MCW-Modern-cloud-apps#83]
Hi there,

In Exercise 2->task 3->subtask 2->step 4, I am correctly prompted for AAD credentials, I can successfully authenticate and get access to the web app, but at the right hand side it will still say "Sign in" instead of logged in, any ideas what might be wrong?

**Comment by kylebunting** [comment]
@Dacuna16, this appears to be an issue with the code being used in the Admin app to validate whether or not the user is authenticated and logged in. I can confirm that I see the same issue, and am awaiting feedback from Microsoft on how they want to proceed with a fix.

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #87
