### ISSUE TITLE
MULTIPLE ISSUES FACED WHILE PERFORMING THE LAB

### ISSUE THREAD

**Issue by Eddevinc** [microsoft/MCW-Modern-cloud-apps#85]
Hello team here are few of the issues faced by us during performing the lab.

**Major Issues**: 
1. Not able to add items to the cart/ Not able to place orders in the contoso sports website.
2. Exercise 5, Task 4, Subtask 2, Step 33: getting json error in code of logic app 
3. Exercise 2, Task 3, Subtask 2 , Step 4: in the upper-right corner login option not coming

**Other Issues**

**EXERCISE 1 
Task 1 
Subtask 7** 
Step 3: Following code already exist in the project file, following step needs to be removed from lab guide 

**Task 2 
Subtask 1** 
Step 3: Geo-Replication is under data management, not setting 
 
Step 4 to Step 10: Instructions need to be updated 

**Subtask 2** 
Step 3: Failover groups is under data management not settings 
 
**Subtask 3** 
Step 3: Failover groups is under data management not settings 

**Task 3 
Subtask 3** 
Step 3: Following code already exist in the project file, following step needs to be removed from lab guide 
Step 6: It says to edit file under “Contoso.Apps.SportsLeague.web” whereas it should be “Contoso.Apps.SportsLeague.Admin” instead. 

Subtask 4 
Step 3: Following code already exist in the project file, following step needs to be removed from lab guide 

**Task 5 
Subtask 4** 
 Step 3: Following code already exists in the project file, following step needs to be removed from lab guide 

 
**Exercise 2** 

**Task 1:** Needs to be updated as there is no option available under company branding for buying free trial for Azure AD Premium P2. 

**Task 3 
Subtask 2** 
Step 4: in the upper-right corner sign in comes not login

**Task 4** 
Step 4: in the upper-right corner sign in comes 

**Exercise 3** 

**Task 1:** 'Microsoft.AzureActiveDirectory’ needs to be registered to create a new Active Directory. 
**Task 9** 
Step 4: Claims button not working. Sign in and Signup option not there 

**Exercise 4** 

**Task 1 
Subtask 2** 
step4: Code already exists in the file. 
 
**Subtask 3** 
Step 5: not able to publish orders. 

**Exercise 5 
Task 4 
Subtask 2:** 
Step 33: getting json error in code of logic app 

 
**Exercise 6** 
**Task 2** 
CMD Commands to set github account is not mentioned.

**Comment by timahenning** [comment]
Hi @Eddevinc,

Thank you for the notification.  The labs are solutions with many dependencies.  At times, Azure is updated and the solution breaks or the instructions need updating.  This problem has occurred in this workshop.  Modern Cloud apps is scheduled for an update to address these issues.  Because there are several areas that need work, it will take more than 10 business days.  It will be closer to 3 to 4 weeks.

Tim

**Comment by akn9050** [comment]
@timahenning @DawnmarieDesJardins  can this be priorities, we have lab requests for 3rd June.

**Comment by timahenning** [comment]
Hi @akn9050,
We will try to deliver this 4 - 5 business days before June 3rd.
Tim

**Comment by akn9050** [comment]
Hi @timahenning @DawnmarieDesJardins, 

Hope you are doing well!

Just wanted to check if you have any update on this issue, actually we are getting close to the scheduled workshop.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #87
