### ISSUE TITLE
HTTP Error 500.30 in End of Ex1 - Task 1

### ISSUE THREAD

**Issue by saeinc** [microsoft/MCW-Modern-cloud-apps#86]
In the end of ex1-task1, when I tried to publish the app service, I can get error message and didnt show any web page. 
The error page is attached. 

![image](https://user-images.githubusercontent.com/42832609/119607351-1df0e900-be2f-11eb-90ed-e6fdfed21048.png)

**Comment by kylebunting** [comment]
@saeinc, please validate your configuration settings and check that you have updated the code according to the instructions in the lab guide. I have run through the lab several times and have not been able to reproduce this error.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #87
