### ISSUE TITLE
ex6-task1 issue

### ISSUE THREAD

**Issue by saeinc** [microsoft/MCW-Modern-cloud-apps#88]
Hi, All. 
I'm doing this HOL and there is an issue to create API Apps (Ex6-task1). 
There is no API Apps in marketplace now so how can I handle this? 

Please fix this issue. :) 

Thank you

**Comment by kylebunting** [comment]
@saeinc, can you please verify that you are typing "API App" into the search the marketplace box?

![image](https://user-images.githubusercontent.com/5960229/120485967-98b38a00-c382-11eb-8954-70ab76f8adbe.png)

When I do this and press enter, I am taken to the blade to create a new API App, so they definitely still exist in the Azure portal.

![image](https://user-images.githubusercontent.com/5960229/120486067-aff27780-c382-11eb-8265-3a0a148c3f5d.png)

**Comment by kylebunting** [comment]
@saeinc, did the above approach help you to resolve the issue you were experiencing?

**Comment by saeinc** [comment]
Hi @Kyle bunting, 
Thanks for your reply but in my PAYG subscription, I still can't see the API App service :( 
I submitted support ticket to Azure Support team regarding this case.

**Comment by kylebunting** [comment]
@saeinc, as an alternative, you can provision a **Web App** in Azure. API and Web Apps are both the same thing, so it won't make a difference for completing the lab.

**Comment by kylebunting** [comment]
@saeinc, I'm going to close out this issue. If you are unable to get a resolution from MS support, please proceed to use a **Web App** in place of the API App in the instructions.
