### ISSUE TITLE
Application Error on Exercise 4: Deploy the Call Center admin website

### ISSUE THREAD

**Issue by zagruby** [microsoft/MCW-Modern-cloud-apps#89]
Deploying Call Center admin website is resulting in Application Error. Not sure if this change something:
- I verified connection string and they were fine.
- I was trying to deploy on both Linux and Windows machine
- the e-commerce website works fine, so the App configuration and key-vault connection shoudl be fine
Any ideas?

**Comment by codingbandit** [comment]
I was able to reproduce this issue. Investigating...

**Comment by codingbandit** [comment]
@zagruby - I have issued a PR for this fix, please downgrade the Microsoft.AspNetCore.Authorization nuget package to version 3.1.18 and your application should deploy successfully

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge off PR #90
